//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id { get; set; }
        public string nomape { get; set; }
        public string nomuser { get; set; }
        public string passuser { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ultLogin { get; set; }
        public int idRol { get; set; }
        public string nomRol { get; set; }
        public System.DateTime fecreg { get; set; }
    }
}
